### ISSUE TITLE
Update to v0.55.0

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.github.utsushi.Utsushi#4]
https://gitlab.com/utsushi/utsushi/

**Comment by LeandroStanger** [comment]
@cosimoc Utsushi needs to be updated

**Comment by LeandroStanger** [comment]
@utsushi

**Comment by nedrichards** [comment]
Fixed with https://github.com/flathub/com.github.utsushi.Utsushi/commit/236c9b6d805eeee8258c73350106c0dad825f248
