### ISSUE TITLE
App not appearing in flathub.org because is using an stock icon

### ISSUE THREAD

**Issue by jgarciao** [flathub/com.github.utsushi.Utsushi#7]
This app is not appearing in flathub.org because the webapp doesn't support stock icons:
```
<icon type="stock">scanner</icon>
```
Is the same issue than this: https://github.com/flathub/org.gnome.font-viewer/issues/1

Could you please add 64x64 and 128x128 icons?

**Comment by AsciiWolf** [comment]
Still the same issue, however the app appears now, but with no icon.

**Comment by nedrichards** [comment]
Fixed with https://github.com/flathub/com.github.utsushi.Utsushi/commit/236c9b6d805eeee8258c73350106c0dad825f248

https://flathub.org/apps/details/com.github.utsushi.Utsushi
